[package]
name = "hello-rust-aws-s3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#aws-config = "1.1.1"
#aws-sdk-s3 = "1.11.0"
tokio = { version = "1.35.1", features = ["full"] }
